---
provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  require_ansible_repo: false
  require_ansible_omnibus: true

driver:
  name: docker

platforms:
  - name: debian-7.8
    driver_config:
      image: dynatrace/debian-testing:7.8

suites:
  - name: default
