---
- name: Create the installation directory {{ dynatrace_collector_linux_install_dir }}
  file: path="{{ dynatrace_collector_linux_install_dir }}" state=directory
  register: dynatrace_collector_create_install_dir_result
  sudo: yes

- name: Change ownership of the installation directory if it had to be created
  file: path="{{ dynatrace_collector_linux_install_dir }}" owner=dynatrace group=dynatrace
  when: dynatrace_collector_create_install_dir_result|changed
  sudo: yes

- name: Copy the Dynatrace Collector installer to {{ dynatrace_collector_linux_install_dir }}
  copy: src="{{ playbook_dir }}/roles/{{ dynatrace_collector_role_name }}/files/linux/{{ dynatrace_collector_linux_installer_file_name }}" dest="{{ dynatrace_collector_linux_install_dir }}"
  sudo: yes

- name: Copy the Dynatrace Collector installer script to /tmp
  template: src=../../templates/linux/run-dynatrace-collector-installer.sh.j2 dest=/tmp/run-dynatrace-collector-installer.sh

- name: Stop and disable running Dynatrace Collector services
  service: name={{ item }} state=stopped enabled=no
  with_items: dynatrace_collector_linux_service_names
  sudo: yes
  ignore_errors: yes

- name: Sleep for 5 seconds...
  pause: seconds=5

- name: Install the Dynatrace Collector
  shell: /bin/bash /tmp/run-dynatrace-collector-installer.sh
  sudo: yes

- name: Gather the name of the installation directory
  shell: find . -maxdepth 1 -name dynatrace-\* -type d -printf '%T@ %p\n' | sort -k 1nr | cut -d' ' -f2 | head -1 chdir={{ dynatrace_collector_linux_install_dir }}
  register: dynatrace_collector_installed_version_dir
  sudo: yes

- name: Change ownership of the installation directory
  file: path={{ dynatrace_collector_linux_install_dir }}/{{ dynatrace_collector_installed_version_dir.stdout }} owner=dynatrace group=dynatrace state=directory recurse=yes
  sudo: yes

- name: Change mode of the installation directory
  file: path={{ dynatrace_collector_linux_install_dir }}/{{ dynatrace_collector_installed_version_dir.stdout }} mode=0755
  sudo: yes

- name: Create a symlink of the actual installation directory to {{ dynatrace_collector_linux_install_dir }}/dynatrace
  file: src={{ dynatrace_collector_linux_install_dir }}/{{ dynatrace_collector_installed_version_dir.stdout }} dest={{ dynatrace_collector_linux_install_dir }}/dynatrace owner=dynatrace group=dynatrace mode=0755 state=link
  sudo: yes

- name: Remove the Dynatrace Collector installer
  file: path="{{ dynatrace_collector_linux_install_dir }}/{{ dynatrace_collector_linux_installer_file_name }}" state=absent
  sudo: yes

- name: Compute the Dynatrace Collector's start runlevels for Ubuntu and Debian based distros
  set_fact:
    linux_service_start_runlevels="2 3 4 5"
    linux_service_stop_runlevels="0 1 6"
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

- name: Compute the Dynatrace Collector's start runlevels
  set_fact:
    linux_service_start_runlevels="3 5"
    linux_service_stop_runlevels="0 1 2 6"
  when: ansible_distribution == 'CentOS' or ansible_distribution == 'Red Hat Enterprise Linux'

- name: Make the 'dynaTraceCollector' init script available in /etc/init.d
  template: src=../../templates/linux/init.d/dynaTraceCollector.j2 dest=/etc/init.d/dynaTraceCollector owner=root group=root mode=0755
  sudo: yes

- name: Enable and start Dynatrace Collector services
  service: name={{ item }} state=restarted sleep=5 enabled=yes
  with_items: dynatrace_collector_linux_service_names
  sudo: yes
