---
- name: Update APT cache
  apt: update_cache=yes
  sudo: yes
  ignore_errors: yes

- name: Check if 'java' is on the PATH
  shell: which java
  sudo: yes
  ignore_errors: yes
  register: which_java_cmd

- name: Install package 'default-jre-headless'
  apt: pkg=default-jre-headless state=present
  register: java_install
  when: which_java_cmd.rc != 0
  sudo: yes
